### DISCUSSION TITLE
Couldn't get Serverless to work properly with "Manage routes from code"

### DISCUSSION THREAD

**Discussion by alexdonh** [TypedProject/ts-express-decorators#1655] [Q&A] [answered]
@Romakita Hey it's me again!

I am experimenting Serverless platform but it got me a little confused. I was following https://tsed.io/tutorials/serverless.html#manage-routes-from-code but I couldn't get "Manage routes from code" to work. Do you have a working example? 

Also, I see that `serverless-offline` plugin is installed but you are running `serverless invoke local...` Is that intended?

**Comment by Romakita** [comment, marked as answer]
Hello @alexdonh 
I'm sorry, I miss to give a command example to invoke the lambda with a router :/

Add this task on your package.json:

```json
"scripts": {
    "invoke:any": "serverless invoke local -f any --data '{\"path\":\"/timeslots\", \"httpMethod\": \"GET\"}'"
}
```
See you

**Reply by alexdonh** [reply]
In `serverless.yml` this one is intended too `handler: dist/handler.handler` ? Any other changes needed in `handler.ts` ?

**Reply by alexdonh** [reply]
I got

```
Serverless Error ----------------------------------------
 
  Lambda handler "dist/handler" does not point function property
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.6
     Framework Version:         2.66.2 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
 
error Command failed with exit code 1.
```

**Reply by Romakita** [reply]
You have to build your code before

**Reply by Romakita** [reply]
The build task depend on your stack. It's recommended to build lambda with webpack instead of tsc

**Reply by alexdonh** [reply]
i indeed built with tsc. the thing is i got it working with this

```
hello:
    handler: dist/handler.hello <==== 
    events:
      - http:
          path: /hello
          method: get
```

```
$ tsc --project tsconfig.compile.json
{
    "statusCode": 200,
    "body": "Hello, world!",
    "headers": {
        "x-request-id": "74a3a343-0161-4cae-969c-fc743028fab2"
    },
    "isBase64Encoded": false
}
✨  Done in 4.24s.
```

but not this 

```
any:
    handler: dist/handler.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
```

in `handler.ts`,  do i need to do something about `export = platform.callbacks()` as it looks like the `callbacks()` return a list of functions exported from the lambdas.
