### DISCUSSION TITLE
using `@Examples()` on a model

### DISCUSSION THREAD

**Discussion by VictoriqueMoe** [TypedProject/ts-express-decorators#2631] [General]
hello.

I have the following decorator  in my argument:
```ts
@QueryParams("expires")
@Examples({
	empty: {
		summary: "empty",
		description: "expires according to retention policy",
		value: "",
	},
	"1d": {
		summary: "1d",
		description: "expires in 1day",
		value: "1d",
	},
})
@Description(
	"a string containing a number and a letter of `m` for mins, `h` for hours, `d` for days. For example: `1h` would be 1 hour and `1d` would be 1 day. leave this blank if you want the file to exist according to the retention policy",
)
@Pattern(/^$|^\d+[mhd]$/)
customExpiry?: string,
```
this is a Parameter.

I like this because in swagger, you can get a dropdown of all the eamples 
![image](https://github.com/tsedio/tsed/assets/27996712/6f24a5d2-cbbe-449b-946a-a5290c574f23)
![image](https://github.com/tsedio/tsed/assets/27996712/ed4a8993-e806-436e-864f-a1c0d6d5c9ab)

I am now moving all the `@QueryParams` to an model object to not pollute the class. my object looks as follows:

```ts
@Name("WaifuUploadParameters")
@Description("Upload parameters for put requests")
export class FileUploadParameters {
    @Description(
        "a string containing a number and a letter of `m` for mins, `h` for hours, `d` for days. For example: `1h` would be 1 hour and `1d` would be 1 day. leave this blank if you want the file to exist according to the retention policy",
    )
    @Pattern(/^$|^\d+[mhd]$/)
    @Property()
    public expires?: string;

    @Description(
        "if set to true, then your filename will not appear in the URL. if false, then it will appear in the URL. defaults to false",
    )
    @Property()
    public hide_filename?: boolean;

    @Description(
        "Set a password for this file, this will encrypt the file on the server that not even the server owner can obtain it, when fetching the file. you can fill out the `x-password` http header with your password to obtain the file via API",
    )
    @Property()
    public password?: string;

    @Description("Shh, it's a secret ;)")
    @Property()
    public secret_token?: string;
}
```
I want the examples to stay for `expires`. however the `@Examples()` decorator is only a `ParameterDecorator` and the non-plural version `@Example()` does not do the same thing, all that seems to do is fill in the input with a default value. not a dropdown like `@Examples()`

Is there a way so that the model can have `Examples()` and it renders in the swagger of a deropdown of examples?

**Comment by VictoriqueMoe** [comment]
FYI, this PR on my application is for this change for additinal context https://github.com/waifuvault/WaifuVault/pull/131

**Reply by Romakita** [reply]
Hello @VictoriqueMoe 
I'll take a time to look the swagger editor. The Examples field on swagger is only available for parameters:

```yml
/pet/findByTags:
    get:
      tags:
        - pet
      summary: Finds Pets by tags
      description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
      operationId: findPetsByTags
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: false
          examples:
            test:
              description: test
              value: {"id": "id"}
          schema:
            type: object
            properties:
               id: 
                 type: string
```

Swagger doesn't accept `examples` on schema level:

<img width="824" alt="Capture d’écran 2024-03-22 à 07 39 41" src="https://github.com/tsedio/tsed/assets/1763311/fb29a8d7-cd0e-46eb-9a2f-5cdd40e61c7c">

It example why I restricted `Examples` usage to `ParameterDecorator` only.

But in this case, Ts.ED transform given Query model to have a field (Input, Select in swagger UI) for each model properties. The `Examples` decorator doesn't seems to be applicable due to this transformation. I have to create a custom decorator to apply examples on a specific properties for a Query model ^^. I tried different workaround but it doesn't works.

I'll come back to you when I have a solution ;)
