### ISSUE TITLE
[BUG] `Example()` used in conjuction with `CollectionOf()` produce wrong OAS definition

### ISSUE THREAD

**Issue by ostridm** [TypedProject/ts-express-decorators#2047]
## Information

- **Version:** 6.118
- Packages: @tsed/schema

Unexpected `example` value placement when `Example()` decorator is applied to property in conjuction with `CollectionOf()` 

## Example

```ts
import {} from "@tsed/schema";

export class Foo{
  @Example('exampleValue')
  @MaxLength(10)
  @CollectionOf(String)
  public someCollection?: string[];
}
```
produces 

```yaml
    Foo:
      type: object
      properties:
        someCollection:
          type: array
          items:
            type: string
            maxLength: 10
          example: exampleValue
```

instead of the expected one 
```diff
    Foo:
      type: object
      properties:
        someCollection:
          type: array
          items:
            type: string
            maxLength: 10
+           example: exampleValue
-         example: exampleValue
```

It seems the root cause is in the wrong schema node reference inside decorator implementation. `MaxLength` refers to [`store.itemSchema`](https://github.com/tsedio/tsed/blob/5df4564051a28e64d70b5c98d3f30501b8e9e6e7/packages/specs/schema/src/decorators/common/maxLength.ts#L84   
) while `Example` refers to [`store.schema`](https://github.com/tsedio/tsed/blob/5df4564051a28e64d70b5c98d3f30501b8e9e6e7/packages/specs/schema/src/decorators/common/example.ts#L16) 

## Acceptance criteria

- [ ] excpect correct OAS definition
